version: '3.4'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./.env
    volumes:
      - '.:/home/app/scsbuster'
    ports:
      - '3001:80'
