# Load the Rails application.
require_relative 'application'

# Initialize the Rails application.
Rails.application.initialize!

API_BASE_URL=ENV['API_BASE_URL']
AWS_KEY_ID=ENV['AWS_KEY_ID']
AWS_SECRET=ENV['AWS_SECRET']
OAUTH_CALLBACK_URL = ENV['OAUTH_CALLBACK_URL']
OAUTH_AUTH_URL = ENV['OAUTH_AUTH_URL']
OAUTH_SITE = ENV['OAUTH_SITE']
OAUTH_LOGIN_URL= ENV['OAUTH_LOGIN_URL']
REFILE_REQUEST_SECRET = ENV['REFILE_REQUEST_SECRET']
