name: CI

on:
  pull_request:
    branches:
      - qa
      - production

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build and test
        run: |
          docker-compose build
          docker-compose up -d
          docker-compose exec webapp bash -c 'RAILS_ENV=test bundle exec rspec'
