name: CI

on:
  pull_request:
    branches:
      - qa
      - production

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up docker
        uses: docker/setup-buildx-action@v2

      - name: install docker dompose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: build and test
        run: |
          touch .env
          docker-compose build
          docker-compose up -d --no-tty
          docker-compose exec webapp bash -c 'RAILS_ENV=test bundle exec rspec'
